spring.application.name=fieldstd

server.port=8030

spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/field_db
spring.datasource.username=postgres
spring.datasource.password=Password
spring.main.allow-circular-references=true


# Application URLs (for email links)
app.frontend-url=http://localhost:5174
app.api-url=http://localhost:8030


# Actuator for Health Checks
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

# Log to file
logging.file.name=application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Show full exception stack traces
server.error.include-stacktrace=always
server.error.include-message=always
